apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: flask-build-pipeline
spec:
  workspaces:
    - name: source

  params:
    - name: git-url
      type: string
    - name: git-revision
      type: string
      default: main
    - name: image-url
      type: string

  tasks:
    - name: clone-repository
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
      workspaces:
        - name: output
          workspace: source
      params:
        - name: URL
          value: $(params.git-url)
        - name: REVISION
          value: $(params.git-revision)
        - name: DELETE_EXISTING
          value: "true"

    - name: build-and-push
      runAfter:
        - clone-repository
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: buildah
          - name: namespace
            value: openshift-pipelines
      workspaces:
        - name: source
          workspace: source
      params:
        - name: IMAGE
          value: $(params.image-url)
        - name: TLSVERIFY
          value: "false"