apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-triggers-pipelinerun-role
rules:
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
      - taskruns
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - tekton.dev
    resources:
      - pipelines
      - tasks
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-triggers-pipelinerun-rolebinding
subjects:
  - kind: ServiceAccount
    name: pipeline
roleRef:
  kind: Role
  name: tekton-triggers-pipelinerun-role
  apiGroup: rbac.authorization.k8s.io
