apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: github-eventlistener
spec:
  to:
    kind: Service
    name: el-github-eventlistener
  port:
    targetPort: http-listener
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
