apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: flask-build-run-
spec:
  pipelineRef:
    name: flask-build-pipeline

  params:
    - name: git-url
      value: "https://github.com/DelucaSZ/RHOS_tekton_lab.git"
    - name: git-revision
      value: "main"
    - name: image-url
      value: "image-registry.openshift-image-registry.svc:5000/tekton-lab/flask-app:latest"

  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi